@baseUrl = https://canojoel-examenexpress-1.onrender.com/api/mascotas
@contentType = application/json

GET {{baseUrl}}/

### id 1
GET {{baseUrl}}/1

### id 2
GET {{baseUrl}}/2

### id 3
GET {{baseUrl}}/3

### id 4
GET {{baseUrl}}/4

### id 5
GET {{baseUrl}}/5

### comprobacion de mensaje y status
GET {{baseUrl}}/999

### comprobar que añade mascotas
POST {{baseUrl}}/
Content-Type: {{contentType}}

{
    "nombre": "Wilson Jr",
    "especie": "Gato"
}

### comprobar que añade mascotas - Perro
POST {{baseUrl}}/
Content-Type: {{contentType}}

{
    "nombre": "Rex",
    "especie": "Perro"
}

### comprobar que añade mascotas - Pájaro
POST {{baseUrl}}/
Content-Type: {{contentType}}

{
    "nombre": "Tweety",
    "especie": "Pájaro"
}

### comprobar que añade mascotas - Sin nombre (error esperado)
POST {{baseUrl}}/
Content-Type: {{contentType}}

{
    "especie": "Hamster"
}
