@baseUrl = https://canojoel-examenexpress.onrender.com/api/mascotas


GET {{baseUrl}}/

### id 1
GET {{baseUrl}}/1

### id 2
GET {{baseUrl}}/2

### id 3
GET {{baseUrl}}/3

### id 4
GET {{baseUrl}}/4

### id 5
GET {{baseUrl}}/5

### comprobacion de mensaje y status
GET {{baseUrl}}/999

